name: checkout
on:
  push:
    branches: 
      - main
defaults:
  run:
    shell: bash
jobs:
  checkingout:
    runs-on: ubuntu-22.04
    steps:
      - name: Before
        run: ls -a
      - name: Checkingout
        uses: actions/checkout@v4
      - name: After
        run: ls -a