name: Contexts
on:
  push:
    branches: 
      - main

  pull_request:
    branches: 
      - main 

  issues: 
    types: 
      - opened

  workflow_dispatch:
    inputs:
      Sidhu:
        default: boy
        required: true
        type: string

run-name: "Expressions and Context by @${{ github.actor }}, Event is : ${{ github.event_name }}, ${{ github.ref_name }}"

defaults:
  run:
    shell: bash

jobs:
  checkout_job:
    runs-on: ubuntu-22.04
    if: contains(fromJson('["issues", "pull_request"]'), github.event_name) || github.event_name == 'push'
    steps:      
      - uses: actions/checkout@v4
      - run: ls -a
  sidhu_job:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'