name: get-current-directory
on:
  push:
    branches: 
      - main

defaults:
  run:
    shell: bash


jobs:
  new_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Step1
        run: |
          ls
          ls -a
          pwd
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
  second_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Step1
        run: |
          ls -l
          echo $HOSTNAME
          date +"%d-%m-%Y-%H:%M:%S-%B-%A"
    needs: 
      - new_job