name: First Workflow
on:
  push: 
    branches: 
      - main

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "hello"
            - name: multi
              run: |
                node -v
                npm -v
    
    parallel_jobs:
      runs-on: macos-latest
      steps:
        - name: MACOS spec command
          run: sw_vers
      needs: 
        - run-shell-commands

    parallel_job_two:
      runs-on: windows-latest
      steps:
        - name: Windows SPEC command
          run: dir
      needs: 
        - run-shell-commands

