name: First Workflow
on:
    - push

jobs:
    run-shell-commands:
        runs_on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "hello"
            - name: multi
              run: |
                node -v
                npm -v

