name: TestingEvents
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened
jobs:
  jobone:
    runs-on: ubuntu-22.04
    steps:
      - name: print few VARS
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - name: checkout-now
        uses: actions/checkout@v4
